export const REQUEST_RESULTS = 'REQUEST_RESULTS'
export const RECEIVE_RESULTS_SUCCESS = 'RECEIVE_RESULTS_SUCCESS'
export const RECEIVE_RESULTS_ERROR = 'RECEIVE_RESULTS_ERROR'

export const TOGGLE_LIKE_STATUS = 'TOGGLE_LIKE_STATUS'
